[bases.content]
C = [[2, 2], ["w", "l", "r", "m", "n", "z", "s", "v", "f", "ȷ", "c", "x", "h", "d", "t", "b", "p", "đ", "ŧ", "g", "k"]]
V = [[1, 1], ["ə", "a", "y", "o", "e", "u", "ı"]]

[bases.guiding]
wildcard = ["#", "@", ""]
separator = [" ", ".", ""]
embedder = [["-", "-"], [":", ";"], ["", ""]]

[modifiers]
swapper = [[{ V = "̈" }, { C = "ː" }], [{ C = "ː" }, { V = "̈" }]]

[modifiers.breaker]
V = [["̀", "́̄"]]

[substitutions.free]
"̂" = "̈́"
"̌" = "̈̀"
"̃" = "̈̄"
"'" = "ə"
">" = "-"
"<" = "-"
"`" = "-ə"
"–" = "--"
"," = ":"
"?" = "."
"!" = "."

[substitutions.elongator]
C = "ː"
