# Alphabet
# The characters of which language elements can be comprised

# Bases
# Characters that are parsed as independent tokens
bases:
  # Content characters carry semantic load and come in classes
  # The number of classes and their compositions are arbitrary
  content:
    C: [ 'wlrmnzsvfȷcxhdtbpđŧgk' ]
    V: [ 'əayoeuı' ]
  # Guiding characters are not intrinsically meaningful
  # Each group must have the length equal to the number of language levels
  # Each group member must be either a singular character or a list of them
  guiding:
    # Wildcards match to any number of continuous nodes that permit them
    wildcard: [ '#', '@', '' ]
    # Separators are placed between compounds
    separator: [ ' ', '.', '' ]
    # Embedders surround embedded elements
    # Each member of this group is a pair of opening and closing characters
    embedder:
    - [ '-', '-' ]
    - [ ':', ';' ]
    - [ '', '' ]

# Modifiers
# Characters that combine with content characters into the same tokens
# Can only combine with characters of corresponding class
# Only applicable to the bottom level
modifiers:
  # Breakers force skip a number of masks equal to their index
  # Breaker groups are split into classes taken from content characters 
  # Each group class member must be a singular character 
  breaker:
    V:
    - [ '̀', '́̄' ]
  # Swappers come in pairs and mark content characters that will have 
  # their tokens swapped with each other during tokenization
  # Swapper groups are pairs of dicts where swapping characters are assigned
  # to content classes to which they are applicable
  swapper:
  - [ { 'V': '̈' }, { 'C': 'ː' } ]
  - [ { 'C': 'ː' }, { 'V': '̈' } ]

# Substitutions
# Pairings of  chars to be replaced by the tokenizer and strings to replace them with
# Only singular characters can be replaced in this way
# Does not account for the decomposition of combined characters that is always performed
substitutions: { ̂: ̈́, ̌: ̈̀, ̃: ̈̄, '''': ə, '>': '-', <: '-', '`': -ə, –: --, ',': ':', '?': ., '!': . }
