ctypes = [
  { "" = { Proform = { ranks = ["", "*+-*", ""] }, Conjunction = { ranks = ["", "*-+*", ""] }, "Content word" = { ranks = ["", "*++*", ""] } }, 1 = { Modulator = { ranks = ["", "-*1-", ""], cpos = [0, 0, 0] }, Connector = { ranks = ["", "11--", ""], cpos = [0, 0, 1] }, Classifier = { ranks = ["", "--11", ""], cpos = [1, 1, 1] }, Determiner = { ranks = ["", "-1*-", ""], cpos = [1, 1, 0] } } },
  { "" = { Predicate-only = { ranks = ["", "+-", ""] }, "Full sentence" = { ranks = ["", "++", ""] } } },
  { "" = { Text = { ranks = [""] } } },
]

ptypes = [
  { Neutral = { swaps = [] } },
  { Encapsulation = { swaps = [[2, 3]] } },
  { Subsummation = { swaps = [[4, 5]] } },
]
